### PR TITLE
upgrade cli package, fix drone 1.x token env variable issue

### LINKED ISSUE #119: Token not being found
Hello

I am having trouble with the token in drone. My yaml is as follows

```yaml
image: nytimes/drone-gke:k8s-1.11
expand_env_vars: true
token: >
   $$GOOGLE_CREDS
```

It is still saying that token is not set, but that env var is set as as secret
```

Drone GKE Plugin built from 88679fcb947304ea35dde46ed60db3ce315c4a9d
--
 Missing required param: token
```

From the docs you say you need to put it in secrets? And then I see blogs about putting it in the higher level where I have done. Can this be cleared up for me? I can run it locally by setting the env var to token, so not sure why the plugin is not working

### PR DESCRIPTION
**Pull request by oliver-nyt**
This should fix #119 by picking up both the `PLUGIN_TOKEN` (drone 1.x) and `TOKEN`(drone 0.x) env variables (see [main.go line 93](https://github.com/nytimes/drone-gke/pull/127/files#diff-7ddfb3e035b42cd70649cc33393fe32cR93))
I upgraded the cli package to v2 before I noticed that you can do this in v1 as well. I can undo that change if you prefer so.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -77,104 +77,104 @@ func wrapMain() error {
...
+			Usage:   "dump available vars and the generated Kubernetes manifest, keeping secrets hidden",
+			EnvVars: []string{"PLUGIN_VERBOSE"},
 		},
-		cli.StringFlag{
-			Name:   "token",
-			Usage:  "service account's JSON credentials",
-			EnvVar: "TOKEN",
+		&cli.StringFlag{
+			Name:    "token",
+			Usage:   "service account's JSON credentials (drone 1.x)",
```
Comment (montmanu) [inline main.go:92]: since this will also still work for <1.x, might be confusing to include the `(drone 1.x)` note in the usage here?

Comment (oliver-nyt) [reply main.go:92]: Ah yes, good catch, that's an artifact from an earlier attempt to fix this, let me remove it.

**Comment by oliver-nyt** [comment]
Thanks for the comments @montmanu - i updated the docs and Makefile but still trying to get the tests to work, I don't think `cli.NewContext()` parses and populates the flags but trying to confirm that right now.

File: main_test.go [hunk 2]
```diff
@@ -540,3 +540,51 @@ func TestPrintTrimmedError(t *testing.T) {
...
+    os.Setenv("TOKEN", "from-token-env")
+    os.Setenv("PLUGIN_TOKEN", "from-plugin-token-env")
+
+    // Set token CLI argument
+    set := flag.NewFlagSet("prefer-arg-over-any-env", 0)
+    c := cli.NewContext(nil, set, nil)
+    set.String("token", "from-token-arg", "")
+
+    // token CLI argument takes precedence over either environment variable
+    assert.Equal(t, "from-token-arg", c.String("token"))
```
Comment (oliver-nyt) [inline main_test.go:558]: @montmanu - there more I think about these tests, the less they make sense.
This would really just tests that the library is working, none of this invokes code any plugin code
(i also still haven't figured out how to trigger env parsing of flags without using the full `cli.App()` thing but that's another problem)
Thoughts?

Comment (montmanu) [reply main_test.go]: i agree that its not testing much of the plugin's code, but its also a somewhat critical part of the plugin's public API, so a bit worried that from a user's e2e POV, we're not well covered on the token parsing / selection logic..

maybe it would be easier for us to figure out a way to cover that via e2e tests? build the plugin, trigger some downstream ci process that would run that version of the plugin against all versions of drone supported by the plugin?

File: README.md [hunk 3]
```diff
@@ -50,7 +50,7 @@ Executing locally from the working directory:
 cd local-example/
 
 # Set to the path of your GCP service account JSON-formatted key file
-export TOKEN=xxx
+export JSON_TOKEN_FILE=xxx
```
Comment (montmanu) [inline README.md:53]: 😍

File: main_test.go (hunk 2 above)
Comment (oliver-nyt) [reply main_test.go]: Agreed this is important. Let me try something, i think i have an idea what might work.

Comment (oliver-nyt) [reply main_test.go]: Ok, I think I found a way to get the tests to do something meaningful. Might actually want to replace some others like `TestCheckParams` with the same App.Run() pattern to test the real plugin-code.
